apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels: 
    env: demo
    type: frontend
spec:
  containers:
  - name: redis-container
    image: redis/redis-stack
    ports:
    - containerPort: 80